[package]
name = "ray"
version = "0.1.0"
authors = ["bootandy <bootandy@gmail.com>"]

[dependencies]
derive_more = "*"
rand = "0.5.5" # 0.7 had big performance regression
rayon = "*"
itertools = "*"
lazy_static = "*"
image = "*"

